---
title: "prob_sim"
author: "Oswaldo Felix"
date: "4/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


```{r}
# Simulates catches given shiny rate and provides average number needed to ensure shiny catch
shiny_rate <- 20

if(shiny_rate > 200){ #max number of runs =1000
  runs = 1000
} else{
  runs = shiny_rate*5
}

results <- vector('numeric', length = runs)
 
for (i in 1:runs){
  catch <- 0 # reset 
  poke <- vector('numeric', length = runs) # reset
  while (!shiny_rate%in%poke){ # check if shiny is in poke vector
    catch <- catch + 1 # catch pokemon
    p <- sample(1:shiny_rate, 1) # check shiny value
    poke[catch] <- p #store pokemon shiny value
  }
  print(paste("Shiny caught!!", catch))
  results[i] <- catch
}
 
avg = mean(results)
```

```{r}
# Does the same as above, but also makes a chart
shiny_rate <- 512

if(shiny_rate > 200){ #max number of runs =1000
  runs = 1000
} else{
  runs = 750
}
results <- vector('numeric', length = runs)
 
for (i in 1:runs){
  catch <- 0 # reset 
  poke <- vector('numeric', length = runs) # reset
  while (!(shiny_rate %in% poke)){ # check if shiny value contained in poke vector
    catch <- catch + 1 # catch pokemon
    p <- sample(1:shiny_rate, 1) # check shiny value
    poke[catch] <- p #store pokemon shiny value
  }
  print(paste("Shiny caught!!", catch))
  results[i] <- catch
}
 
avg = mean(results)
median = median(results)
min = min(results)
max = max(results)

plot <- as.data.frame(results)
ggplot(data = plot)+
  geom_histogram(aes(x = results, y = ..density..),
                 color = "darkgrey", fill = "lightblue",
                 alpha = 0.6)+
  geom_density(aes(x = results, y = ..density..), color = "darkblue")+
  geom_segment(x = avg, xend = avg,
               y = 0, yend = 2/shiny_rate,
               color = "red", size= 1, linetype = "dashed") +
  geom_segment(x = median, xend = median,
               y = 0, yend = 2/shiny_rate,
               color = "orange", size= 1, linetype = "dashed") +
  geom_text(label = paste("Average:", as.character(round(avg))), color = "red", 
            x = (shiny_rate*2), y = 0.5/shiny_rate) + 
  geom_text(label = paste("Median:", as.character(round(median))), color = "orange", 
            x = (shiny_rate*2), y = 0.45/shiny_rate) + 
  theme_bw()+
  labs(x = "Shiny Catch", y = "")

```

